# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/workspace/zoo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/workspace/zoo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ubuntu/workspace/zoo/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Tests\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/zoo/CMakeFiles /home/ubuntu/workspace/zoo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/zoo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/ubuntu/workspace/zoo/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zoo_platform_static

# Build rule for target.
zoo_platform_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_platform_static
.PHONY : zoo_platform_static

# fast build rule for target.
zoo_platform_static/fast:
	$(MAKE) $(MAKESILENT) -f src/platform/CMakeFiles/zoo_platform_static.dir/build.make src/platform/CMakeFiles/zoo_platform_static.dir/build
.PHONY : zoo_platform_static/fast

#=============================================================================
# Target rules for targets named zoo_platform_shared

# Build rule for target.
zoo_platform_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_platform_shared
.PHONY : zoo_platform_shared

# fast build rule for target.
zoo_platform_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/platform/CMakeFiles/zoo_platform_shared.dir/build.make src/platform/CMakeFiles/zoo_platform_shared.dir/build
.PHONY : zoo_platform_shared/fast

#=============================================================================
# Target rules for targets named zoo_platform_tests

# Build rule for target.
zoo_platform_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_platform_tests
.PHONY : zoo_platform_tests

# fast build rule for target.
zoo_platform_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/platform/tests/CMakeFiles/zoo_platform_tests.dir/build.make src/platform/tests/CMakeFiles/zoo_platform_tests.dir/build
.PHONY : zoo_platform_tests/fast

#=============================================================================
# Target rules for targets named zoo_util_static

# Build rule for target.
zoo_util_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_util_static
.PHONY : zoo_util_static

# fast build rule for target.
zoo_util_static/fast:
	$(MAKE) $(MAKESILENT) -f src/util/CMakeFiles/zoo_util_static.dir/build.make src/util/CMakeFiles/zoo_util_static.dir/build
.PHONY : zoo_util_static/fast

#=============================================================================
# Target rules for targets named zoo_util_shared

# Build rule for target.
zoo_util_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_util_shared
.PHONY : zoo_util_shared

# fast build rule for target.
zoo_util_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/util/CMakeFiles/zoo_util_shared.dir/build.make src/util/CMakeFiles/zoo_util_shared.dir/build
.PHONY : zoo_util_shared/fast

#=============================================================================
# Target rules for targets named util_unity

# Build rule for target.
util_unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 util_unity
.PHONY : util_unity

# fast build rule for target.
util_unity/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/util_unity.dir/build.make src/util/tests/CMakeFiles/util_unity.dir/build
.PHONY : util_unity/fast

#=============================================================================
# Target rules for targets named test_timestamp_unity

# Build rule for target.
test_timestamp_unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_timestamp_unity
.PHONY : test_timestamp_unity

# fast build rule for target.
test_timestamp_unity/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/test_timestamp_unity.dir/build.make src/util/tests/CMakeFiles/test_timestamp_unity.dir/build
.PHONY : test_timestamp_unity/fast

#=============================================================================
# Target rules for targets named test_string_unity

# Build rule for target.
test_string_unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_string_unity
.PHONY : test_string_unity

# fast build rule for target.
test_string_unity/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/test_string_unity.dir/build.make src/util/tests/CMakeFiles/test_string_unity.dir/build
.PHONY : test_string_unity/fast

#=============================================================================
# Target rules for targets named test_memory_unity

# Build rule for target.
test_memory_unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_memory_unity
.PHONY : test_memory_unity

# fast build rule for target.
test_memory_unity/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/test_memory_unity.dir/build.make src/util/tests/CMakeFiles/test_memory_unity.dir/build
.PHONY : test_memory_unity/fast

#=============================================================================
# Target rules for targets named test_math_unity

# Build rule for target.
test_math_unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_math_unity
.PHONY : test_math_unity

# fast build rule for target.
test_math_unity/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/test_math_unity.dir/build.make src/util/tests/CMakeFiles/test_math_unity.dir/build
.PHONY : test_math_unity/fast

#=============================================================================
# Target rules for targets named run_unity_tests

# Build rule for target.
run_unity_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_unity_tests
.PHONY : run_unity_tests

# fast build rule for target.
run_unity_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/run_unity_tests.dir/build.make src/util/tests/CMakeFiles/run_unity_tests.dir/build
.PHONY : run_unity_tests/fast

#=============================================================================
# Target rules for targets named run_timestamp_tests

# Build rule for target.
run_timestamp_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_timestamp_tests
.PHONY : run_timestamp_tests

# fast build rule for target.
run_timestamp_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/run_timestamp_tests.dir/build.make src/util/tests/CMakeFiles/run_timestamp_tests.dir/build
.PHONY : run_timestamp_tests/fast

#=============================================================================
# Target rules for targets named run_string_tests

# Build rule for target.
run_string_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_string_tests
.PHONY : run_string_tests

# fast build rule for target.
run_string_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/run_string_tests.dir/build.make src/util/tests/CMakeFiles/run_string_tests.dir/build
.PHONY : run_string_tests/fast

#=============================================================================
# Target rules for targets named run_memory_tests

# Build rule for target.
run_memory_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_memory_tests
.PHONY : run_memory_tests

# fast build rule for target.
run_memory_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/run_memory_tests.dir/build.make src/util/tests/CMakeFiles/run_memory_tests.dir/build
.PHONY : run_memory_tests/fast

#=============================================================================
# Target rules for targets named run_math_tests

# Build rule for target.
run_math_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_math_tests
.PHONY : run_math_tests

# fast build rule for target.
run_math_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/util/tests/CMakeFiles/run_math_tests.dir/build.make src/util/tests/CMakeFiles/run_math_tests.dir/build
.PHONY : run_math_tests/fast

#=============================================================================
# Target rules for targets named zoo_log_static

# Build rule for target.
zoo_log_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_log_static
.PHONY : zoo_log_static

# fast build rule for target.
zoo_log_static/fast:
	$(MAKE) $(MAKESILENT) -f src/log/CMakeFiles/zoo_log_static.dir/build.make src/log/CMakeFiles/zoo_log_static.dir/build
.PHONY : zoo_log_static/fast

#=============================================================================
# Target rules for targets named zoo_log_shared

# Build rule for target.
zoo_log_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_log_shared
.PHONY : zoo_log_shared

# fast build rule for target.
zoo_log_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/log/CMakeFiles/zoo_log_shared.dir/build.make src/log/CMakeFiles/zoo_log_shared.dir/build
.PHONY : zoo_log_shared/fast

#=============================================================================
# Target rules for targets named zoo_log_tests

# Build rule for target.
zoo_log_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_log_tests
.PHONY : zoo_log_tests

# fast build rule for target.
zoo_log_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/log/tests/CMakeFiles/zoo_log_tests.dir/build.make src/log/tests/CMakeFiles/zoo_log_tests.dir/build
.PHONY : zoo_log_tests/fast

#=============================================================================
# Target rules for targets named log_quick_test

# Build rule for target.
log_quick_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 log_quick_test
.PHONY : log_quick_test

# fast build rule for target.
log_quick_test/fast:
	$(MAKE) $(MAKESILENT) -f src/log/tests/CMakeFiles/log_quick_test.dir/build.make src/log/tests/CMakeFiles/log_quick_test.dir/build
.PHONY : log_quick_test/fast

#=============================================================================
# Target rules for targets named log_test_verbose

# Build rule for target.
log_test_verbose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 log_test_verbose
.PHONY : log_test_verbose

# fast build rule for target.
log_test_verbose/fast:
	$(MAKE) $(MAKESILENT) -f src/log/tests/CMakeFiles/log_test_verbose.dir/build.make src/log/tests/CMakeFiles/log_test_verbose.dir/build
.PHONY : log_test_verbose/fast

#=============================================================================
# Target rules for targets named zoo_memory_pool_static

# Build rule for target.
zoo_memory_pool_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_memory_pool_static
.PHONY : zoo_memory_pool_static

# fast build rule for target.
zoo_memory_pool_static/fast:
	$(MAKE) $(MAKESILENT) -f src/memory_pool/CMakeFiles/zoo_memory_pool_static.dir/build.make src/memory_pool/CMakeFiles/zoo_memory_pool_static.dir/build
.PHONY : zoo_memory_pool_static/fast

#=============================================================================
# Target rules for targets named zoo_memory_pool_shared

# Build rule for target.
zoo_memory_pool_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_memory_pool_shared
.PHONY : zoo_memory_pool_shared

# fast build rule for target.
zoo_memory_pool_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/memory_pool/CMakeFiles/zoo_memory_pool_shared.dir/build.make src/memory_pool/CMakeFiles/zoo_memory_pool_shared.dir/build
.PHONY : zoo_memory_pool_shared/fast

#=============================================================================
# Target rules for targets named zoo_buffer_static

# Build rule for target.
zoo_buffer_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_buffer_static
.PHONY : zoo_buffer_static

# fast build rule for target.
zoo_buffer_static/fast:
	$(MAKE) $(MAKESILENT) -f src/buffer/CMakeFiles/zoo_buffer_static.dir/build.make src/buffer/CMakeFiles/zoo_buffer_static.dir/build
.PHONY : zoo_buffer_static/fast

#=============================================================================
# Target rules for targets named zoo_buffer_shared

# Build rule for target.
zoo_buffer_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_buffer_shared
.PHONY : zoo_buffer_shared

# fast build rule for target.
zoo_buffer_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/buffer/CMakeFiles/zoo_buffer_shared.dir/build.make src/buffer/CMakeFiles/zoo_buffer_shared.dir/build
.PHONY : zoo_buffer_shared/fast

#=============================================================================
# Target rules for targets named zoo_socket_static

# Build rule for target.
zoo_socket_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_socket_static
.PHONY : zoo_socket_static

# fast build rule for target.
zoo_socket_static/fast:
	$(MAKE) $(MAKESILENT) -f src/socket/CMakeFiles/zoo_socket_static.dir/build.make src/socket/CMakeFiles/zoo_socket_static.dir/build
.PHONY : zoo_socket_static/fast

#=============================================================================
# Target rules for targets named zoo_socket_shared

# Build rule for target.
zoo_socket_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_socket_shared
.PHONY : zoo_socket_shared

# fast build rule for target.
zoo_socket_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/socket/CMakeFiles/zoo_socket_shared.dir/build.make src/socket/CMakeFiles/zoo_socket_shared.dir/build
.PHONY : zoo_socket_shared/fast

#=============================================================================
# Target rules for targets named zoo_socket_unity

# Build rule for target.
zoo_socket_unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_socket_unity
.PHONY : zoo_socket_unity

# fast build rule for target.
zoo_socket_unity/fast:
	$(MAKE) $(MAKESILENT) -f src/socket/tests/CMakeFiles/zoo_socket_unity.dir/build.make src/socket/tests/CMakeFiles/zoo_socket_unity.dir/build
.PHONY : zoo_socket_unity/fast

#=============================================================================
# Target rules for targets named zoo_socket_tests

# Build rule for target.
zoo_socket_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_socket_tests
.PHONY : zoo_socket_tests

# fast build rule for target.
zoo_socket_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/socket/tests/CMakeFiles/zoo_socket_tests.dir/build.make src/socket/tests/CMakeFiles/zoo_socket_tests.dir/build
.PHONY : zoo_socket_tests/fast

#=============================================================================
# Target rules for targets named socket_test_verbose

# Build rule for target.
socket_test_verbose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 socket_test_verbose
.PHONY : socket_test_verbose

# fast build rule for target.
socket_test_verbose/fast:
	$(MAKE) $(MAKESILENT) -f src/socket/tests/CMakeFiles/socket_test_verbose.dir/build.make src/socket/tests/CMakeFiles/socket_test_verbose.dir/build
.PHONY : socket_test_verbose/fast

#=============================================================================
# Target rules for targets named zoo_thread_pool_static

# Build rule for target.
zoo_thread_pool_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_thread_pool_static
.PHONY : zoo_thread_pool_static

# fast build rule for target.
zoo_thread_pool_static/fast:
	$(MAKE) $(MAKESILENT) -f src/thread_pool/CMakeFiles/zoo_thread_pool_static.dir/build.make src/thread_pool/CMakeFiles/zoo_thread_pool_static.dir/build
.PHONY : zoo_thread_pool_static/fast

#=============================================================================
# Target rules for targets named zoo_thread_pool_shared

# Build rule for target.
zoo_thread_pool_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_thread_pool_shared
.PHONY : zoo_thread_pool_shared

# fast build rule for target.
zoo_thread_pool_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/thread_pool/CMakeFiles/zoo_thread_pool_shared.dir/build.make src/thread_pool/CMakeFiles/zoo_thread_pool_shared.dir/build
.PHONY : zoo_thread_pool_shared/fast

#=============================================================================
# Target rules for targets named zoo_dispatcher_static

# Build rule for target.
zoo_dispatcher_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_dispatcher_static
.PHONY : zoo_dispatcher_static

# fast build rule for target.
zoo_dispatcher_static/fast:
	$(MAKE) $(MAKESILENT) -f src/dispatcher/CMakeFiles/zoo_dispatcher_static.dir/build.make src/dispatcher/CMakeFiles/zoo_dispatcher_static.dir/build
.PHONY : zoo_dispatcher_static/fast

#=============================================================================
# Target rules for targets named zoo_dispatcher_shared

# Build rule for target.
zoo_dispatcher_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_dispatcher_shared
.PHONY : zoo_dispatcher_shared

# fast build rule for target.
zoo_dispatcher_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/dispatcher/CMakeFiles/zoo_dispatcher_shared.dir/build.make src/dispatcher/CMakeFiles/zoo_dispatcher_shared.dir/build
.PHONY : zoo_dispatcher_shared/fast

#=============================================================================
# Target rules for targets named zoo_timer_static

# Build rule for target.
zoo_timer_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_timer_static
.PHONY : zoo_timer_static

# fast build rule for target.
zoo_timer_static/fast:
	$(MAKE) $(MAKESILENT) -f src/timer/CMakeFiles/zoo_timer_static.dir/build.make src/timer/CMakeFiles/zoo_timer_static.dir/build
.PHONY : zoo_timer_static/fast

#=============================================================================
# Target rules for targets named zoo_timer_shared

# Build rule for target.
zoo_timer_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_timer_shared
.PHONY : zoo_timer_shared

# fast build rule for target.
zoo_timer_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/timer/CMakeFiles/zoo_timer_shared.dir/build.make src/timer/CMakeFiles/zoo_timer_shared.dir/build
.PHONY : zoo_timer_shared/fast

#=============================================================================
# Target rules for targets named zoo_timer_tests

# Build rule for target.
zoo_timer_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_timer_tests
.PHONY : zoo_timer_tests

# fast build rule for target.
zoo_timer_tests/fast:
	$(MAKE) $(MAKESILENT) -f src/timer/tests/CMakeFiles/zoo_timer_tests.dir/build.make src/timer/tests/CMakeFiles/zoo_timer_tests.dir/build
.PHONY : zoo_timer_tests/fast

#=============================================================================
# Target rules for targets named timer_test_clean

# Build rule for target.
timer_test_clean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timer_test_clean
.PHONY : timer_test_clean

# fast build rule for target.
timer_test_clean/fast:
	$(MAKE) $(MAKESILENT) -f src/timer/tests/CMakeFiles/timer_test_clean.dir/build.make src/timer/tests/CMakeFiles/timer_test_clean.dir/build
.PHONY : timer_test_clean/fast

#=============================================================================
# Target rules for targets named timer_test_verbose

# Build rule for target.
timer_test_verbose: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timer_test_verbose
.PHONY : timer_test_verbose

# fast build rule for target.
timer_test_verbose/fast:
	$(MAKE) $(MAKESILENT) -f src/timer/tests/CMakeFiles/timer_test_verbose.dir/build.make src/timer/tests/CMakeFiles/timer_test_verbose.dir/build
.PHONY : timer_test_verbose/fast

#=============================================================================
# Target rules for targets named zoo_smb_static

# Build rule for target.
zoo_smb_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_smb_static
.PHONY : zoo_smb_static

# fast build rule for target.
zoo_smb_static/fast:
	$(MAKE) $(MAKESILENT) -f src/smb/CMakeFiles/zoo_smb_static.dir/build.make src/smb/CMakeFiles/zoo_smb_static.dir/build
.PHONY : zoo_smb_static/fast

#=============================================================================
# Target rules for targets named zoo_smb_shared

# Build rule for target.
zoo_smb_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_smb_shared
.PHONY : zoo_smb_shared

# fast build rule for target.
zoo_smb_shared/fast:
	$(MAKE) $(MAKESILENT) -f src/smb/CMakeFiles/zoo_smb_shared.dir/build.make src/smb/CMakeFiles/zoo_smb_shared.dir/build
.PHONY : zoo_smb_shared/fast

#=============================================================================
# Target rules for targets named test_zoo_smb_subscription_session_manager_unit

# Build rule for target.
test_zoo_smb_subscription_session_manager_unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_zoo_smb_subscription_session_manager_unit
.PHONY : test_zoo_smb_subscription_session_manager_unit

# fast build rule for target.
test_zoo_smb_subscription_session_manager_unit/fast:
	$(MAKE) $(MAKESILENT) -f smb/tests/CMakeFiles/test_zoo_smb_subscription_session_manager_unit.dir/build.make smb/tests/CMakeFiles/test_zoo_smb_subscription_session_manager_unit.dir/build
.PHONY : test_zoo_smb_subscription_session_manager_unit/fast

#=============================================================================
# Target rules for targets named fuzz_zoo_smb_protocol

# Build rule for target.
fuzz_zoo_smb_protocol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fuzz_zoo_smb_protocol
.PHONY : fuzz_zoo_smb_protocol

# fast build rule for target.
fuzz_zoo_smb_protocol/fast:
	$(MAKE) $(MAKESILENT) -f tests/fuzz/CMakeFiles/fuzz_zoo_smb_protocol.dir/build.make tests/fuzz/CMakeFiles/fuzz_zoo_smb_protocol.dir/build
.PHONY : fuzz_zoo_smb_protocol/fast

#=============================================================================
# Target rules for targets named zoo_integration_unity

# Build rule for target.
zoo_integration_unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoo_integration_unity
.PHONY : zoo_integration_unity

# fast build rule for target.
zoo_integration_unity/fast:
	$(MAKE) $(MAKESILENT) -f tests/integration/CMakeFiles/zoo_integration_unity.dir/build.make tests/integration/CMakeFiles/zoo_integration_unity.dir/build
.PHONY : zoo_integration_unity/fast

#=============================================================================
# Target rules for targets named test_zoo_smb_integration

# Build rule for target.
test_zoo_smb_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_zoo_smb_integration
.PHONY : test_zoo_smb_integration

# fast build rule for target.
test_zoo_smb_integration/fast:
	$(MAKE) $(MAKESILENT) -f tests/integration/CMakeFiles/test_zoo_smb_integration.dir/build.make tests/integration/CMakeFiles/test_zoo_smb_integration.dir/build
.PHONY : test_zoo_smb_integration/fast

#=============================================================================
# Target rules for targets named test_service_discovery

# Build rule for target.
test_service_discovery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_service_discovery
.PHONY : test_service_discovery

# fast build rule for target.
test_service_discovery/fast:
	$(MAKE) $(MAKESILENT) -f tests/integration/CMakeFiles/test_service_discovery.dir/build.make tests/integration/CMakeFiles/test_service_discovery.dir/build
.PHONY : test_service_discovery/fast

#=============================================================================
# Target rules for targets named test_backpressure_security

# Build rule for target.
test_backpressure_security: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_backpressure_security
.PHONY : test_backpressure_security

# fast build rule for target.
test_backpressure_security/fast:
	$(MAKE) $(MAKESILENT) -f tests/integration/CMakeFiles/test_backpressure_security.dir/build.make tests/integration/CMakeFiles/test_backpressure_security.dir/build
.PHONY : test_backpressure_security/fast

#=============================================================================
# Target rules for targets named test_zoo_smb_transport_udp

# Build rule for target.
test_zoo_smb_transport_udp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_zoo_smb_transport_udp
.PHONY : test_zoo_smb_transport_udp

# fast build rule for target.
test_zoo_smb_transport_udp/fast:
	$(MAKE) $(MAKESILENT) -f tests/integration/CMakeFiles/test_zoo_smb_transport_udp.dir/build.make tests/integration/CMakeFiles/test_zoo_smb_transport_udp.dir/build
.PHONY : test_zoo_smb_transport_udp/fast

#=============================================================================
# Target rules for targets named test_zoo_smb_transport_shm

# Build rule for target.
test_zoo_smb_transport_shm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_zoo_smb_transport_shm
.PHONY : test_zoo_smb_transport_shm

# fast build rule for target.
test_zoo_smb_transport_shm/fast:
	$(MAKE) $(MAKESILENT) -f tests/integration/CMakeFiles/test_zoo_smb_transport_shm.dir/build.make tests/integration/CMakeFiles/test_zoo_smb_transport_shm.dir/build
.PHONY : test_zoo_smb_transport_shm/fast

#=============================================================================
# Target rules for targets named test_zoo_smb_transport_tcp

# Build rule for target.
test_zoo_smb_transport_tcp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_zoo_smb_transport_tcp
.PHONY : test_zoo_smb_transport_tcp

# fast build rule for target.
test_zoo_smb_transport_tcp/fast:
	$(MAKE) $(MAKESILENT) -f tests/integration/CMakeFiles/test_zoo_smb_transport_tcp.dir/build.make tests/integration/CMakeFiles/test_zoo_smb_transport_tcp.dir/build
.PHONY : test_zoo_smb_transport_tcp/fast

#=============================================================================
# Target rules for targets named e2e_performance_benchmark

# Build rule for target.
e2e_performance_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 e2e_performance_benchmark
.PHONY : e2e_performance_benchmark

# fast build rule for target.
e2e_performance_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f tests/benchmark/CMakeFiles/e2e_performance_benchmark.dir/build.make tests/benchmark/CMakeFiles/e2e_performance_benchmark.dir/build
.PHONY : e2e_performance_benchmark/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... log_quick_test"
	@echo "... log_test_verbose"
	@echo "... run_math_tests"
	@echo "... run_memory_tests"
	@echo "... run_string_tests"
	@echo "... run_timestamp_tests"
	@echo "... run_unity_tests"
	@echo "... socket_test_verbose"
	@echo "... timer_test_clean"
	@echo "... timer_test_verbose"
	@echo "... e2e_performance_benchmark"
	@echo "... fuzz_zoo_smb_protocol"
	@echo "... test_backpressure_security"
	@echo "... test_math_unity"
	@echo "... test_memory_unity"
	@echo "... test_service_discovery"
	@echo "... test_string_unity"
	@echo "... test_timestamp_unity"
	@echo "... test_zoo_smb_integration"
	@echo "... test_zoo_smb_subscription_session_manager_unit"
	@echo "... test_zoo_smb_transport_shm"
	@echo "... test_zoo_smb_transport_tcp"
	@echo "... test_zoo_smb_transport_udp"
	@echo "... util_unity"
	@echo "... zoo_buffer_shared"
	@echo "... zoo_buffer_static"
	@echo "... zoo_dispatcher_shared"
	@echo "... zoo_dispatcher_static"
	@echo "... zoo_integration_unity"
	@echo "... zoo_log_shared"
	@echo "... zoo_log_static"
	@echo "... zoo_log_tests"
	@echo "... zoo_memory_pool_shared"
	@echo "... zoo_memory_pool_static"
	@echo "... zoo_platform_shared"
	@echo "... zoo_platform_static"
	@echo "... zoo_platform_tests"
	@echo "... zoo_smb_shared"
	@echo "... zoo_smb_static"
	@echo "... zoo_socket_shared"
	@echo "... zoo_socket_static"
	@echo "... zoo_socket_tests"
	@echo "... zoo_socket_unity"
	@echo "... zoo_thread_pool_shared"
	@echo "... zoo_thread_pool_static"
	@echo "... zoo_timer_shared"
	@echo "... zoo_timer_static"
	@echo "... zoo_timer_tests"
	@echo "... zoo_util_shared"
	@echo "... zoo_util_static"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/ubuntu/workspace/zoo/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

