#!/usr/bin/env bash
set -euo pipefail

ARTIFACT_DIR="${ARTIFACT_DIR:-artifacts/quality}"
POLICY_FILE="docs/requirements/PROTOCOL_COMPATIBILITY_POLICY.md"
README_FILE="README.md"
RELEASE_TEMPLATE="docs/templates/RELEASE_NOTES_TEMPLATE.md"
LOCAL_MAJOR="${PROTOCOL_MAJOR:-1}"
LOCAL_MINOR="${PROTOCOL_MINOR:-0}"
MIN_SUPPORTED_MINOR="${PROTOCOL_MIN_SUPPORTED_MINOR:-0}"

mkdir -p "${ARTIFACT_DIR}"

for required_file in "${POLICY_FILE}" "${README_FILE}" "${RELEASE_TEMPLATE}"; do
  if [[ ! -f "${required_file}" ]]; then
    echo "Required file not found: ${required_file}" >&2
    exit 1
  fi
done

if ! grep -q "Protocol Compatibility Policy" "${POLICY_FILE}"; then
  echo "Policy file does not contain the expected title" >&2
  exit 1
fi

if ! grep -q "Compatibility And Deprecation" "${README_FILE}"; then
  echo "README is missing the compatibility section" >&2
  exit 1
fi

for required_field in \
  "API compatibility status:" \
  "Wire compatibility status:" \
  "Breaking changes:" \
  "Deprecation notices:"; do
  if ! grep -q "${required_field}" "${RELEASE_TEMPLATE}"; then
    echo "Release notes template is missing required field: ${required_field}" >&2
    exit 1
  fi
done

if (( MIN_SUPPORTED_MINOR > LOCAL_MINOR )); then
  echo "Invalid protocol minor support window: min ${MIN_SUPPORTED_MINOR} exceeds local ${LOCAL_MINOR}" >&2
  exit 1
fi

output_file="${ARTIFACT_DIR}/protocol_compatibility_matrix.md"

status_for_pair() {
  local peer_major="$1"
  local peer_minor="$2"

  if (( peer_major != LOCAL_MAJOR )); then
    printf 'Blocked'
    return
  fi

  if (( peer_minor < MIN_SUPPORTED_MINOR )); then
    printf 'Blocked'
    return
  fi

  if (( peer_minor > LOCAL_MINOR )); then
    printf 'Blocked'
    return
  fi

  if (( peer_minor == LOCAL_MINOR )); then
    printf 'Accepted'
    return
  fi

  printf 'Accepted with downgrade'
}

reason_for_pair() {
  local peer_major="$1"
  local peer_minor="$2"

  if (( peer_major != LOCAL_MAJOR )); then
    printf 'Major mismatch. Fail fast before message exchange.'
    return
  fi

  if (( peer_minor < MIN_SUPPORTED_MINOR )); then
    printf 'Peer minor is older than the supported v%d.%d floor.' "${LOCAL_MAJOR}" "${MIN_SUPPORTED_MINOR}"
    return
  fi

  if (( peer_minor > LOCAL_MINOR )); then
    printf 'Peer minor is newer than the local implementation.'
    return
  fi

  if (( peer_minor == LOCAL_MINOR )); then
    printf 'Exact version match.'
    return
  fi

  printf 'Use shared semantics of v%d.%d.' "${LOCAL_MAJOR}" "${peer_minor}"
}

peer_minor_max=$((LOCAL_MINOR + 1))
peer_minors=()
for ((minor = 0; minor <= peer_minor_max; minor++)); do
  peer_minors+=("${minor}")
done

peer_majors=($((LOCAL_MAJOR - 1)) "${LOCAL_MAJOR}" $((LOCAL_MAJOR + 1)))

{
  echo "# Protocol Compatibility Matrix"
  echo
  printf -- '- Generated by `%s`\n' "tools/quality/protocol_compatibility_matrix.sh"
  printf -- '- Local baseline: `v%d.%d`\n' "${LOCAL_MAJOR}" "${LOCAL_MINOR}"
  printf -- '- Supported peer range within major `%d`: `v%d.%d` to `v%d.%d`\n' \
    "${LOCAL_MAJOR}" "${LOCAL_MAJOR}" "${MIN_SUPPORTED_MINOR}" "${LOCAL_MAJOR}" "${LOCAL_MINOR}"
  echo
  echo "## Rules"
  echo
  echo "- Same major and peer minor less than or equal to local minor: accepted."
  echo "- Same major with older minor revisions within support floor: accepted with downgrade behavior to the lower common minor."
  echo "- Different major or newer peer minor: blocked with fail-fast mismatch handling."
  echo
  echo "## Matrix"
  echo
  echo "| Local | Peer | Result | Reason |"
  echo "|---|---|---|---|"
  for peer_major in "${peer_majors[@]}"; do
    if (( peer_major < 0 )); then
      continue
    fi
    for peer_minor in "${peer_minors[@]}"; do
      status=$(status_for_pair "${peer_major}" "${peer_minor}")
      reason=$(reason_for_pair "${peer_major}" "${peer_minor}")
      printf '| `v%d.%d` | `v%d.%d` | %s | %s |\n' \
        "${LOCAL_MAJOR}" "${LOCAL_MINOR}" "${peer_major}" "${peer_minor}" "${status}" "${reason}"
    done
  done
  echo
  echo "## Release Requirements"
  echo
  echo '- Publish release declarations using `docs/templates/RELEASE_NOTES_TEMPLATE.md`.'
  echo '- Update `docs/requirements/PROTOCOL_COMPATIBILITY_POLICY.md` if the local baseline or support window changes.'
  echo "- Preserve this matrix as a CI artifact for pull requests and protected-branch builds."
} > "${output_file}"

cat "${output_file}"
