/*******************************************************************************
 * Copyright (C) 2025, Basic Software Research Institute ltd
 * All rights reserved.
 * Product: ZOO
 * Module: Soft Message Bus
 * Component id: ZOO_SMB_ERROR
 * File name: zoo_smb_error.h
 * Description: Comprehensive error handling system for ZOO SMB
 * History recorder:
 * Version   date           author            context
 * 1.0       2025-05-14     weiwang.sun       created
 * 2.0       2025-06-23     weiwang.sun    Deep optimization with systematic design
 ******************************************************************************/

#ifndef ZOO_SMB_ERROR_H
#define ZOO_SMB_ERROR_H

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stdint.h>
#include <time.h>
#include "../../platform/inc/zoo.h"
#include "zoo_error.h" // Use parent ZOO error system

    // ==============================================================================
    // ERROR CODE ARCHITECTURE
    // ==============================================================================

    /**
     * @brief Error code structure (using parent ZOO error system)
     *
     * Using parent ZOO error system with SMB-specific range (-1200 to -1299)
     * For compatibility with existing SMB code, we alias ZOO_ERROR_T to ZOO_ERROR_TYPE
     */
    typedef ZOO_ERROR_T ZOO_ERROR_TYPE;

// Error code construction macros - using parent ZOO error system
// SMB module uses error range -1200 to -1299 
#define ZOO_SMB_ERROR_BASE              (ZOO_ERROR_RANGE_SMB)       /**< SMB error base */
#define ZOO_SMB_OK                      (ZOO_OK)                    /**< Success alias */
#define ZOO_SMB_SPECIFIC_SHIFT 0

// Error code bit layout definitions
#define ZOO_SMB_ERROR_FLAG_MASK         0x80000000U    /**< Error flag bit */
#define ZOO_SMB_CATEGORY_SHIFT          24             /**< Category bit position */
#define ZOO_SMB_SUBCATEGORY_SHIFT       16             /**< Subcategory bit position */
#define ZOO_SMB_SPECIFIC_SHIFT          0              /**< Specific error bit position */

#define ZOO_SMB_CATEGORY_MASK           0x7F000000U    /**< Category mask */
#define ZOO_SMB_SUBCATEGORY_MASK        0x00FF0000U    /**< Subcategory mask */
#define ZOO_SMB_SPECIFIC_MASK           0x0000FFFFU    /**< Specific error mask */

/**
 * @brief Construct error code from components
 */
#define ZOO_SMB_MAKE_ERROR(category, subcategory, specific)            \
    (ZOO_SMB_ERROR_FLAG_MASK |                                         \
     (((uint32_t)(category) & 0x7F) << ZOO_SMB_CATEGORY_SHIFT) |       \
     (((uint32_t)(subcategory) & 0xFF) << ZOO_SMB_SUBCATEGORY_SHIFT) | \
     ((uint32_t)(specific) & 0xFFFF))

/**
 * @brief Extract components from error code
 */
#define ZOO_SMB_GET_CATEGORY(error) (((uint32_t)(error) & ZOO_SMB_CATEGORY_MASK) >> ZOO_SMB_CATEGORY_SHIFT)
#define ZOO_SMB_GET_SUBCATEGORY(error) (((uint32_t)(error) & ZOO_SMB_SUBCATEGORY_MASK) >> ZOO_SMB_SUBCATEGORY_SHIFT)
#define ZOO_SMB_GET_SPECIFIC(error) ((uint32_t)(error) & ZOO_SMB_SPECIFIC_MASK)

/**
 * @brief Check if error code indicates success or failure
 */
#define ZOO_SMB_IS_SUCCESS(error) (((uint32_t)(error) & ZOO_SMB_ERROR_FLAG_MASK) == 0)
#define ZOO_SMB_IS_ERROR(error) (((uint32_t)(error) & ZOO_SMB_ERROR_FLAG_MASK) != 0)

// ==============================================================================
// SUCCESS CODE (already defined above)
// ==============================================================================
// Note: ZOO_SMB_OK is already defined above as alias to ZOO_OK

    // ==============================================================================
    // ERROR CATEGORIES (0-127)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_CATEGORY_GENERAL = 0,         /**< General errors */
        ZOO_SMB_CATEGORY_MEMORY = 1,          /**< Memory management errors */
        ZOO_SMB_CATEGORY_THREAD = 2,          /**< Threading and synchronization errors */
        ZOO_SMB_CATEGORY_NETWORK = 3,         /**< Network and socket errors */
        ZOO_SMB_CATEGORY_PROTOCOL = 4,        /**< Protocol and message format errors */
        ZOO_SMB_CATEGORY_TRANSPORT = 5,       /**< Transport layer errors */
        ZOO_SMB_CATEGORY_SERVICE = 6,         /**< Service management errors */
        ZOO_SMB_CATEGORY_CONFIG = 7,          /**< Configuration errors */
        ZOO_SMB_CATEGORY_FILESYSTEM = 8,      /**< File system and I/O errors */
        ZOO_SMB_CATEGORY_SECURITY = 9,        /**< Security and permission errors */
        ZOO_SMB_CATEGORY_DATA_STRUCTURE = 10, /**< Data structure errors */
        ZOO_SMB_CATEGORY_HANDSHAKE = 11,      /**< Handshake process errors */
        ZOO_SMB_CATEGORY_ROUTING = 12,        /**< Message routing errors */
        ZOO_SMB_CATEGORY_LOGGING = 13,        /**< Logging system errors */
        ZOO_SMB_CATEGORY_SHARED_MEMORY = 14,  /**< Shared memory errors */
        ZOO_SMB_CATEGORY_RING_BUFFER = 15,    /**< Ring buffer errors */
        ZOO_SMB_CATEGORY_SUBSCRIPTION = 16,   /**< Subscription management errors */
        ZOO_SMB_CATEGORY_PUBLICATION = 17,    /**< Publication errors */
        ZOO_SMB_CATEGORY_DISCOVERY = 18,      /**< Service discovery errors */
        ZOO_SMB_CATEGORY_PERFORMANCE = 19,    /**< Performance monitoring errors */
        ZOO_SMB_CATEGORY_VALIDATION = 20,     /**< Data validation errors */
        ZOO_SMB_CATEGORY_SERIALIZATION = 21,  /**< Serialization/deserialization errors */
        ZOO_SMB_CATEGORY_COMPRESSION = 22,    /**< Compression/decompression errors */
        ZOO_SMB_CATEGORY_ENCRYPTION = 23,     /**< Encryption/decryption errors */
        ZOO_SMB_CATEGORY_STATISTICS = 24,     /**< Statistics collection errors */
        ZOO_SMB_CATEGORY_MAINTENANCE = 25,    /**< System maintenance errors */
        ZOO_SMB_CATEGORY_RESOURCE = 26,       /**< Resource management errors */
        ZOO_SMB_CATEGORY_TIMEOUT = 27,        /**< Timeout related errors */
        ZOO_SMB_CATEGORY_COMPATIBILITY = 28,  /**< Version compatibility errors */
        ZOO_SMB_CATEGORY_EXTENSION = 29,      /**< Extension/plugin errors */
        // Categories 30-127 reserved for future use
    } ZOO_SMB_ERROR_CATEGORY;

    // ==============================================================================
    // GENERAL ERRORS (Category 0)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_GENERAL_PARAM = 0,     /**< Parameter validation */
        ZOO_SMB_GENERAL_STATE = 1,     /**< State management */
        ZOO_SMB_GENERAL_OPERATION = 2, /**< Operation execution */
        ZOO_SMB_GENERAL_RESOURCE = 3,  /**< Resource access */
        ZOO_SMB_GENERAL_SYSTEM = 4,    /**< System level */
    } ZOO_SMB_GENERAL_SUBCATEGORY;

// Parameter validation errors
#define ZOO_SMB_ERROR_INVALID_PARAM ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_PARAM, 1)
#define ZOO_SMB_ERROR_NULL_POINTER ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_PARAM, 2)
#define ZOO_SMB_ERROR_BUFFER_TOO_SMALL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_PARAM, 3)
#define ZOO_SMB_ERROR_INVALID_SIZE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_PARAM, 4)
#define ZOO_SMB_ERROR_OUT_OF_RANGE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_PARAM, 5)
#define ZOO_SMB_ERROR_INVALID_NAME ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_PARAM, 6)  // 新增

// State management errors
#define ZOO_SMB_ERROR_NOT_INITIALIZED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_STATE, 1)
#define ZOO_SMB_ERROR_ALREADY_INITIALIZED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_STATE, 2)
#define ZOO_SMB_ERROR_INVALID_STATE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_STATE, 3)
#define ZOO_SMB_ERROR_NOT_STARTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_STATE, 4)
#define ZOO_SMB_ERROR_ALREADY_STARTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_STATE, 5)

// Operation execution errors
#define ZOO_SMB_ERROR_NOT_SUPPORTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_OPERATION, 1)
#define ZOO_SMB_ERROR_NOT_IMPLEMENTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_OPERATION, 2)
#define ZOO_SMB_ERROR_OPERATION_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_OPERATION, 3)
#define ZOO_SMB_ERROR_INTERRUPTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_OPERATION, 4)

// Resource access errors
#define ZOO_SMB_ERROR_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_RESOURCE, 1)
#define ZOO_SMB_ERROR_ALREADY_EXISTS ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_RESOURCE, 2)
#define ZOO_SMB_ERROR_BUSY ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_RESOURCE, 3)
#define ZOO_SMB_ERROR_AGAIN ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_RESOURCE, 4)

// System level errors
#define ZOO_SMB_ERROR_PROCESS_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_SYSTEM, 1)     // 新增
#define ZOO_SMB_ERROR_PROCESS_CHECK_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_GENERAL, ZOO_SMB_GENERAL_SYSTEM, 2)  // 新增

    // ==============================================================================
    // MEMORY ERRORS (Category 1)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_MEMORY_ALLOCATION = 0, /**< Memory allocation */
        ZOO_SMB_MEMORY_POOL = 1,       /**< Memory pool management */
        ZOO_SMB_MEMORY_CORRUPTION = 2, /**< Memory corruption detection */
        ZOO_SMB_MEMORY_LEAK = 3,       /**< Memory leak detection */
    } ZOO_SMB_MEMORY_SUBCATEGORY;

// Memory allocation errors
#define ZOO_SMB_ERROR_OUT_OF_MEMORY ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_ALLOCATION, 1)
#define ZOO_SMB_ERROR_ALLOCATION_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_ALLOCATION, 2)
#define ZOO_SMB_ERROR_FREE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_ALLOCATION, 3)

// Memory pool errors
#define ZOO_SMB_ERROR_POOL_CREATE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_POOL, 1)
#define ZOO_SMB_ERROR_POOL_DESTROY_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_POOL, 2)
#define ZOO_SMB_ERROR_POOL_CORRUPTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_POOL, 3)
#define ZOO_SMB_ERROR_POOL_EXHAUSTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_POOL, 4)

// Memory corruption errors
#define ZOO_SMB_ERROR_BUFFER_OVERFLOW ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_CORRUPTION, 1)
#define ZOO_SMB_ERROR_BUFFER_UNDERFLOW ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_CORRUPTION, 2)
#define ZOO_SMB_ERROR_INVALID_BLOCK ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_CORRUPTION, 3)
#define ZOO_SMB_ERROR_DOUBLE_FREE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_MEMORY, ZOO_SMB_MEMORY_CORRUPTION, 4)

    // ==============================================================================
    // THREAD ERRORS (Category 2)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_THREAD_LIFECYCLE = 0,       /**< Thread lifecycle */
        ZOO_SMB_THREAD_SYNCHRONIZATION = 1, /**< Synchronization */
        ZOO_SMB_THREAD_SCHEDULING = 2,      /**< Scheduling */
        ZOO_SMB_THREAD_RESOURCE = 3,        /**< Resource management */
    } ZOO_SMB_THREAD_SUBCATEGORY;

// Thread lifecycle errors
#define ZOO_SMB_ERROR_THREAD_CREATE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_LIFECYCLE, 1)
#define ZOO_SMB_ERROR_THREAD_JOIN_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_LIFECYCLE, 2)
#define ZOO_SMB_ERROR_THREAD_DETACH_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_LIFECYCLE, 3)

// Thread synchronization errors
#define ZOO_SMB_ERROR_MUTEX_INIT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_SYNCHRONIZATION, 1)
#define ZOO_SMB_ERROR_MUTEX_LOCK_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_SYNCHRONIZATION, 2)
#define ZOO_SMB_ERROR_MUTEX_UNLOCK_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_SYNCHRONIZATION, 3)
#define ZOO_SMB_ERROR_CONDITION_INIT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_SYNCHRONIZATION, 4)
#define ZOO_SMB_ERROR_CONDITION_WAIT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_SYNCHRONIZATION, 5)
#define ZOO_SMB_ERROR_CONDITION_SIGNAL_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_THREAD, ZOO_SMB_THREAD_SYNCHRONIZATION, 6)

    // ==============================================================================
    // NETWORK ERRORS (Category 3)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_NETWORK_SOCKET = 0,        /**< Socket operations */
        ZOO_SMB_NETWORK_CONNECTION = 1,    /**< Connection management */
        ZOO_SMB_NETWORK_IO = 2,            /**< I/O operations */
        ZOO_SMB_NETWORK_CONFIGURATION = 3, /**< Network configuration */
    } ZOO_SMB_NETWORK_SUBCATEGORY;

// Socket errors
#define ZOO_SMB_ERROR_SOCKET_CREATE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_NETWORK, ZOO_SMB_NETWORK_SOCKET, 1)
#define ZOO_SMB_ERROR_SOCKET_BIND_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_NETWORK, ZOO_SMB_NETWORK_SOCKET, 2)
#define ZOO_SMB_ERROR_SOCKET_LISTEN_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_NETWORK, ZOO_SMB_NETWORK_SOCKET, 3)
#define ZOO_SMB_ERROR_SOCKET_ACCEPT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_NETWORK, ZOO_SMB_NETWORK_SOCKET, 4)
#define ZOO_SMB_ERROR_SOCKET_CONNECT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_NETWORK, ZOO_SMB_NETWORK_SOCKET, 5)

// Network I/O errors
#define ZOO_SMB_ERROR_NETWORK_SEND_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_NETWORK, ZOO_SMB_NETWORK_IO, 1)
#define ZOO_SMB_ERROR_NETWORK_RECV_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_NETWORK, ZOO_SMB_NETWORK_IO, 2)
#define ZOO_SMB_ERROR_NETWORK_IO_ERROR ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_NETWORK, ZOO_SMB_NETWORK_IO, 3)

    // ==============================================================================
    // PROTOCOL ERRORS (Category 4)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_PROTOCOL_MESSAGE = 0,  /**< Message format */
        ZOO_SMB_PROTOCOL_VERSION = 1,  /**< Version compatibility */
        ZOO_SMB_PROTOCOL_SEQUENCE = 2, /**< Message sequence */
        ZOO_SMB_PROTOCOL_STATE = 3,    /**< Protocol state */
    } ZOO_SMB_PROTOCOL_SUBCATEGORY;

// Protocol message errors
#define ZOO_SMB_ERROR_INVALID_MESSAGE_FORMAT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PROTOCOL, ZOO_SMB_PROTOCOL_MESSAGE, 1)
#define ZOO_SMB_ERROR_MESSAGE_TOO_LARGE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PROTOCOL, ZOO_SMB_PROTOCOL_MESSAGE, 2)
#define ZOO_SMB_ERROR_MESSAGE_CORRUPTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PROTOCOL, ZOO_SMB_PROTOCOL_MESSAGE, 3)
#define ZOO_SMB_ERROR_MESSAGE_INCOMPLETE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PROTOCOL, ZOO_SMB_PROTOCOL_MESSAGE, 4)

// Protocol version errors
#define ZOO_SMB_ERROR_VERSION_MISMATCH ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PROTOCOL, ZOO_SMB_PROTOCOL_VERSION, 1)
#define ZOO_SMB_ERROR_VERSION_NOT_SUPPORTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PROTOCOL, ZOO_SMB_PROTOCOL_VERSION, 2)

// Protocol sequence errors
#define ZOO_SMB_ERROR_SEQUENCE_ERROR ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PROTOCOL, ZOO_SMB_PROTOCOL_SEQUENCE, 1)
#define ZOO_SMB_ERROR_DUPLICATE_MESSAGE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PROTOCOL, ZOO_SMB_PROTOCOL_SEQUENCE, 2)

    // ==============================================================================
    // TRANSPORT ERRORS (Category 5)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_TRANSPORT_LIFECYCLE = 0,     /**< Transport lifecycle */
        ZOO_SMB_TRANSPORT_COMMUNICATION = 1, /**< Communication operations */
        ZOO_SMB_TRANSPORT_CONNECTION = 2,    /**< Connection management */
        ZOO_SMB_TRANSPORT_CONSUMER = 3,      /**< Consumer management */
    } ZOO_SMB_TRANSPORT_SUBCATEGORY;

// Transport lifecycle errors
#define ZOO_SMB_ERROR_TRANSPORT_CREATE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_LIFECYCLE, 1)
#define ZOO_SMB_ERROR_TRANSPORT_INIT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_LIFECYCLE, 2)
#define ZOO_SMB_ERROR_TRANSPORT_START_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_LIFECYCLE, 3)
#define ZOO_SMB_ERROR_TRANSPORT_STOP_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_LIFECYCLE, 4)
#define ZOO_SMB_ERROR_TRANSPORT_DESTROY_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_LIFECYCLE, 5)

// Communication errors
#define ZOO_SMB_ERROR_TRANSPORT_SEND_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_COMMUNICATION, 1)
#define ZOO_SMB_ERROR_TRANSPORT_RECV_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_COMMUNICATION, 2)
#define ZOO_SMB_ERROR_TRANSPORT_MESSAGE_TOO_LARGE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_COMMUNICATION, 3)

// Connection errors
#define ZOO_SMB_ERROR_TRANSPORT_CONNECT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_CONNECTION, 1)
#define ZOO_SMB_ERROR_TRANSPORT_DISCONNECT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_CONNECTION, 2)
#define ZOO_SMB_ERROR_TRANSPORT_CONNECTION_LOST ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_CONNECTION, 3)

// Consumer errors
#define ZOO_SMB_ERROR_TRANSPORT_CONSUMER_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_CONSUMER, 1)
#define ZOO_SMB_ERROR_TRANSPORT_CONSUMER_EXISTS ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TRANSPORT, ZOO_SMB_TRANSPORT_CONSUMER, 2)

    // ==============================================================================
    // SERVICE ERRORS (Category 6)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_SERVICE_LIFECYCLE = 0,    /**< Service lifecycle */
        ZOO_SMB_SERVICE_REGISTRATION = 1, /**< Service registration */
        ZOO_SMB_SERVICE_DISCOVERY = 2,    /**< Service discovery */
        ZOO_SMB_SERVICE_HEALTH = 3,       /**< Service health */
    } ZOO_SMB_SERVICE_SUBCATEGORY;

// Service lifecycle errors
#define ZOO_SMB_ERROR_SERVICE_START_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SERVICE, ZOO_SMB_SERVICE_LIFECYCLE, 1)
#define ZOO_SMB_ERROR_SERVICE_STOP_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SERVICE, ZOO_SMB_SERVICE_LIFECYCLE, 2)
#define ZOO_SMB_ERROR_SERVICE_RESTART_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SERVICE, ZOO_SMB_SERVICE_LIFECYCLE, 3)

// Service registration errors
#define ZOO_SMB_ERROR_SERVICE_REGISTER_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SERVICE, ZOO_SMB_SERVICE_REGISTRATION, 1)
#define ZOO_SMB_ERROR_SERVICE_UNREGISTER_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SERVICE, ZOO_SMB_SERVICE_REGISTRATION, 2)
#define ZOO_SMB_ERROR_SERVICE_ALREADY_REGISTERED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SERVICE, ZOO_SMB_SERVICE_REGISTRATION, 3)

// Service discovery errors
#define ZOO_SMB_ERROR_SERVICE_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SERVICE, ZOO_SMB_SERVICE_DISCOVERY, 1)
#define ZOO_SMB_ERROR_SERVICE_UNAVAILABLE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SERVICE, ZOO_SMB_SERVICE_DISCOVERY, 2)

    // ==============================================================================
    // CONFIG ERRORS (Category 7)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_CONFIG_FILE = 0,       /**< Configuration file */
        ZOO_SMB_CONFIG_PARSE = 1,      /**< Configuration parsing */
        ZOO_SMB_CONFIG_VALIDATION = 2, /**< Configuration validation */
        ZOO_SMB_CONFIG_ACCESS = 3,     /**< Configuration access */
    } ZOO_SMB_CONFIG_SUBCATEGORY;

// Config file errors
#define ZOO_SMB_ERROR_CONFIG_FILE_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_CONFIG, ZOO_SMB_CONFIG_FILE, 1)
#define ZOO_SMB_ERROR_CONFIG_FILE_READ_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_CONFIG, ZOO_SMB_CONFIG_FILE, 2)
#define ZOO_SMB_ERROR_CONFIG_FILE_WRITE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_CONFIG, ZOO_SMB_CONFIG_FILE, 3)

// Config parsing errors
#define ZOO_SMB_ERROR_CONFIG_PARSE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_CONFIG, ZOO_SMB_CONFIG_PARSE, 1)
#define ZOO_SMB_ERROR_CONFIG_INVALID_FORMAT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_CONFIG, ZOO_SMB_CONFIG_PARSE, 2)

// Config validation errors
#define ZOO_SMB_ERROR_CONFIG_INVALID_VALUE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_CONFIG, ZOO_SMB_CONFIG_VALIDATION, 1)
#define ZOO_SMB_ERROR_CONFIG_MISSING_REQUIRED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_CONFIG, ZOO_SMB_CONFIG_VALIDATION, 2)

    // ==============================================================================
    // FILESYSTEM ERRORS (Category 8)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_FILESYSTEM_FILE = 0,       /**< File operations */
        ZOO_SMB_FILESYSTEM_DIRECTORY = 1,  /**< Directory operations */
        ZOO_SMB_FILESYSTEM_PERMISSION = 2, /**< Permission errors */
        ZOO_SMB_FILESYSTEM_SPACE = 3,      /**< Space/quota errors */
    } ZOO_SMB_FILESYSTEM_SUBCATEGORY;

// File operation errors
#define ZOO_SMB_ERROR_FILE_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_FILE, 1)
#define ZOO_SMB_ERROR_FILE_OPEN_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_FILE, 2)
#define ZOO_SMB_ERROR_FILE_READ_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_FILE, 3)
#define ZOO_SMB_ERROR_FILE_WRITE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_FILE, 4)
#define ZOO_SMB_ERROR_FILE_CLOSE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_FILE, 5)

// Directory operation errors
#define ZOO_SMB_ERROR_DIR_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_DIRECTORY, 1)
#define ZOO_SMB_ERROR_DIR_CREATE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_DIRECTORY, 2)
#define ZOO_SMB_ERROR_DIR_DELETE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_DIRECTORY, 3)

// Permission errors
#define ZOO_SMB_ERROR_PERMISSION_DENIED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_PERMISSION, 1)
#define ZOO_SMB_ERROR_ACCESS_DENIED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_PERMISSION, 2)

// Space/quota errors
#define ZOO_SMB_ERROR_DISK_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_SPACE, 1)
#define ZOO_SMB_ERROR_QUOTA_EXCEEDED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_FILESYSTEM, ZOO_SMB_FILESYSTEM_SPACE, 2)

    // ==============================================================================
    // SECURITY ERRORS (Category 9)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_SECURITY_AUTHENTICATION = 0, /**< Authentication */
        ZOO_SMB_SECURITY_AUTHORIZATION = 1,  /**< Authorization */
        ZOO_SMB_SECURITY_CERTIFICATE = 2,    /**< Certificate management */
        ZOO_SMB_SECURITY_CRYPTO = 3,         /**< Cryptographic operations */
    } ZOO_SMB_SECURITY_SUBCATEGORY;

// Authentication errors
#define ZOO_SMB_ERROR_AUTH_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_AUTHENTICATION, 1)
#define ZOO_SMB_ERROR_AUTH_REQUIRED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_AUTHENTICATION, 2)
#define ZOO_SMB_ERROR_AUTH_EXPIRED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_AUTHENTICATION, 3)

// Authorization errors
#define ZOO_SMB_ERROR_UNAUTHORIZED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_AUTHORIZATION, 1)
#define ZOO_SMB_ERROR_FORBIDDEN ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_AUTHORIZATION, 2)

// Certificate errors
#define ZOO_SMB_ERROR_CERT_INVALID ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_CERTIFICATE, 1)
#define ZOO_SMB_ERROR_CERT_EXPIRED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_CERTIFICATE, 2)
#define ZOO_SMB_ERROR_CERT_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_CERTIFICATE, 3)

// Cryptographic errors
#define ZOO_SMB_ERROR_CRYPTO_INIT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_CRYPTO, 1)
#define ZOO_SMB_ERROR_ENCRYPT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_CRYPTO, 2)
#define ZOO_SMB_ERROR_DECRYPT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SECURITY, ZOO_SMB_SECURITY_CRYPTO, 3)

    // ==============================================================================
    // DATA STRUCTURE ERRORS (Category 10)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_DATA_STRUCTURE_LIST = 0,  /**< List operations */
        ZOO_SMB_DATA_STRUCTURE_HASH = 1,  /**< Hash table operations */
        ZOO_SMB_DATA_STRUCTURE_TREE = 2,  /**< Tree operations */
        ZOO_SMB_DATA_STRUCTURE_QUEUE = 3, /**< Queue operations */
    } ZOO_SMB_DATA_STRUCTURE_SUBCATEGORY;

// List errors
#define ZOO_SMB_ERROR_LIST_EMPTY ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_LIST, 1)
#define ZOO_SMB_ERROR_LIST_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_LIST, 2)
#define ZOO_SMB_ERROR_LIST_INDEX_OUT_OF_BOUNDS ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_LIST, 3)

// Hash table errors
#define ZOO_SMB_ERROR_HASH_KEY_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_HASH, 1)
#define ZOO_SMB_ERROR_HASH_KEY_EXISTS ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_HASH, 2)
#define ZOO_SMB_ERROR_HASH_TABLE_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_HASH, 3)

// Tree errors
#define ZOO_SMB_ERROR_TREE_NODE_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_TREE, 1)
#define ZOO_SMB_ERROR_TREE_INVALID_PATH ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_TREE, 2)

// Queue errors
#define ZOO_SMB_ERROR_QUEUE_EMPTY ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_QUEUE, 1)
#define ZOO_SMB_ERROR_QUEUE_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DATA_STRUCTURE, ZOO_SMB_DATA_STRUCTURE_QUEUE, 2)

    // ==============================================================================
    // HANDSHAKE ERRORS (Category 11)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_HANDSHAKE_PROCESS = 0, /**< Handshake process */
        ZOO_SMB_HANDSHAKE_MESSAGE = 1, /**< Handshake messages */
        ZOO_SMB_HANDSHAKE_TIMEOUT = 2, /**< Handshake timeouts */
        ZOO_SMB_HANDSHAKE_STATE = 3,   /**< Handshake state */
    } ZOO_SMB_HANDSHAKE_SUBCATEGORY;

// Handshake process errors
#define ZOO_SMB_ERROR_HANDSHAKE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_HANDSHAKE, ZOO_SMB_HANDSHAKE_PROCESS, 1)
#define ZOO_SMB_ERROR_HANDSHAKE_REJECTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_HANDSHAKE, ZOO_SMB_HANDSHAKE_PROCESS, 2)
#define ZOO_SMB_ERROR_HANDSHAKE_VERSION_MISMATCH ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_HANDSHAKE, ZOO_SMB_HANDSHAKE_PROCESS, 3)

// Handshake message errors
#define ZOO_SMB_ERROR_HANDSHAKE_INVALID_MESSAGE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_HANDSHAKE, ZOO_SMB_HANDSHAKE_MESSAGE, 1)
#define ZOO_SMB_ERROR_HANDSHAKE_MESSAGE_FORMAT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_HANDSHAKE, ZOO_SMB_HANDSHAKE_MESSAGE, 2)
#define ZOO_SMB_ERROR_HANDSHAKE_SEND_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_HANDSHAKE, ZOO_SMB_HANDSHAKE_MESSAGE, 3)

// Handshake timeout errors
#define ZOO_SMB_ERROR_HANDSHAKE_TIMEOUT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_HANDSHAKE, ZOO_SMB_HANDSHAKE_TIMEOUT, 1)
#define ZOO_SMB_ERROR_HANDSHAKE_ACK_TIMEOUT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_HANDSHAKE, ZOO_SMB_HANDSHAKE_TIMEOUT, 2)

    // ==============================================================================
    // ROUTING ERRORS (Category 12) - 这是缺失的关键错误码
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_ROUTING_RULE = 0,   /**< Routing rule management */
        ZOO_SMB_ROUTING_TABLE = 1,  /**< Routing table operations */
        ZOO_SMB_ROUTING_PATH = 2,   /**< Path resolution */
        ZOO_SMB_ROUTING_POLICY = 3, /**< Routing policy */
    } ZOO_SMB_ROUTING_SUBCATEGORY;

// Routing rule errors
#define ZOO_SMB_ERROR_ROUTING_RULE_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_RULE, 1)
#define ZOO_SMB_ERROR_ROUTING_RULE_EXISTS ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_RULE, 2)
#define ZOO_SMB_ERROR_ROUTING_RULE_INVALID ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_RULE, 3)
#define ZOO_SMB_ERROR_ROUTING_RULE_DISABLED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_RULE, 4)
#define ZOO_SMB_ERROR_ROUTING_RULE_PREPARE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_RULE, 5)

// Routing table errors
#define ZOO_SMB_ERROR_ROUTING_TABLE_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_TABLE, 1)
#define ZOO_SMB_ERROR_ROUTING_TABLE_EMPTY ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_TABLE, 2)
#define ZOO_SMB_ERROR_ROUTING_TABLE_CORRUPTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_TABLE, 3)

// Path resolution errors
#define ZOO_SMB_ERROR_ROUTING_PATH_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_PATH, 1)
#define ZOO_SMB_ERROR_ROUTING_PATH_INVALID ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_PATH, 2)
#define ZOO_SMB_ERROR_ROUTING_PATH_BLOCKED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_PATH, 3)

// Routing policy errors
#define ZOO_SMB_ERROR_ROUTING_POLICY_VIOLATION ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_POLICY, 1)
#define ZOO_SMB_ERROR_ROUTING_POLICY_CONFLICT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_ROUTING, ZOO_SMB_ROUTING_POLICY, 2)

    // ==============================================================================
    // LOGGING ERRORS (Category 13)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_LOGGING_INIT = 0,     /**< Logging initialization */
        ZOO_SMB_LOGGING_CONFIG = 1,   /**< Logging configuration */
        ZOO_SMB_LOGGING_OUTPUT = 2,   /**< Logging output */
        ZOO_SMB_LOGGING_ROTATION = 3, /**< Log rotation */
    } ZOO_SMB_LOGGING_SUBCATEGORY;

// Logging initialization errors
#define ZOO_SMB_ERROR_LOG_INIT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_LOGGING, ZOO_SMB_LOGGING_INIT, 1)
#define ZOO_SMB_ERROR_LOG_ALREADY_INITIALIZED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_LOGGING, ZOO_SMB_LOGGING_INIT, 2)

// Logging configuration errors
#define ZOO_SMB_ERROR_LOG_CONFIG_INVALID ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_LOGGING, ZOO_SMB_LOGGING_CONFIG, 1)
#define ZOO_SMB_ERROR_LOG_LEVEL_INVALID ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_LOGGING, ZOO_SMB_LOGGING_CONFIG, 2)

// Logging output errors
#define ZOO_SMB_ERROR_LOG_WRITE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_LOGGING, ZOO_SMB_LOGGING_OUTPUT, 1)
#define ZOO_SMB_ERROR_LOG_FILE_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_LOGGING, ZOO_SMB_LOGGING_OUTPUT, 2)

// Log rotation errors
#define ZOO_SMB_ERROR_LOG_ROTATION_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_LOGGING, ZOO_SMB_LOGGING_ROTATION, 1)
#define ZOO_SMB_ERROR_LOG_BACKUP_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_LOGGING, ZOO_SMB_LOGGING_ROTATION, 2)

    // ==============================================================================
    // SHARED MEMORY ERRORS (Category 14)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_SHM_LIFECYCLE = 0,       /**< Shared memory lifecycle */
        ZOO_SMB_SHM_ACCESS = 1,          /**< Access operations */
        ZOO_SMB_SHM_SYNCHRONIZATION = 2, /**< Synchronization */
        ZOO_SMB_SHM_DATA = 3,            /**< Data operations */
    } ZOO_SMB_SHM_SUBCATEGORY;

// Shared memory lifecycle errors
#define ZOO_SMB_ERROR_SHM_CREATE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_LIFECYCLE, 1)
#define ZOO_SMB_ERROR_SHM_ATTACH_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_LIFECYCLE, 2)
#define ZOO_SMB_ERROR_SHM_DETACH_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_LIFECYCLE, 3)
#define ZOO_SMB_ERROR_SHM_DESTROY_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_LIFECYCLE, 4)

// Access errors
#define ZOO_SMB_ERROR_SHM_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_ACCESS, 1)
#define ZOO_SMB_ERROR_SHM_ALREADY_EXISTS ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_ACCESS, 2)
#define ZOO_SMB_ERROR_SHM_PERMISSION_DENIED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_ACCESS, 3)

// Synchronization errors
#define ZOO_SMB_ERROR_SHM_LOCK_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_SYNCHRONIZATION, 1)
#define ZOO_SMB_ERROR_SHM_UNLOCK_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_SYNCHRONIZATION, 2)
#define ZOO_SMB_ERROR_SHM_SEM_CREATE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_SYNCHRONIZATION, 3)
#define ZOO_SMB_ERROR_SHM_SYNCHRONIZATION_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_SYNCHRONIZATION, 4)
#define ZOO_SMB_ERROR_EVENTFD_CREATION_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_SYNCHRONIZATION, 5)  // 新增的错误码

// Data errors
#define ZOO_SMB_ERROR_SHM_BUFFER_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_DATA, 1)
#define ZOO_SMB_ERROR_SHM_INVALID_MESSAGE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_DATA, 2)
#define ZOO_SMB_ERROR_SHM_VERSION_MISMATCH ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_DATA, 3)
#define ZOO_SMB_ERROR_SHM_DATA_INVALID_MAGIC ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_DATA, 4)
#define ZOO_SMB_ERROR_SHM_DATA_VERSION_MISMATCH ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_DATA, 5)
#define ZOO_SMB_ERROR_SHM_DATA_CORRUPTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SHARED_MEMORY, ZOO_SMB_SHM_DATA, 6)

    // ==============================================================================
    // RING BUFFER ERRORS (Category 15)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_RINGBUF_LIFECYCLE = 0, /**< Ring buffer lifecycle */
        ZOO_SMB_RINGBUF_OPERATION = 1, /**< Operations */
        ZOO_SMB_RINGBUF_STATE = 2,     /**< State management */
        ZOO_SMB_RINGBUF_DATA = 3,      /**< Data integrity */
    } ZOO_SMB_RINGBUF_SUBCATEGORY;

// Ring buffer lifecycle errors
#define ZOO_SMB_ERROR_RINGBUF_CREATE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_LIFECYCLE, 1)
#define ZOO_SMB_ERROR_RINGBUF_DESTROY_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_LIFECYCLE, 2)
#define ZOO_SMB_ERROR_RINGBUF_INIT_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_LIFECYCLE, 3)

// Operation errors
#define ZOO_SMB_ERROR_RINGBUF_WRITE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_OPERATION, 1)
#define ZOO_SMB_ERROR_RINGBUF_READ_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_OPERATION, 2)
#define ZOO_SMB_ERROR_RINGBUF_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_OPERATION, 3)
#define ZOO_SMB_ERROR_RINGBUF_EMPTY ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_OPERATION, 4)

// State errors
#define ZOO_SMB_ERROR_RINGBUF_NOT_INITIALIZED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_STATE, 1)
#define ZOO_SMB_ERROR_RINGBUF_INVALID_STATE ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_STATE, 2)
#define ZOO_SMB_ERROR_RINGBUF_NOT_OWNER ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_STATE, 3)

// Data integrity errors
#define ZOO_SMB_ERROR_RINGBUF_CORRUPTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_DATA, 1)
#define ZOO_SMB_ERROR_RINGBUF_OVERFLOW ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_DATA, 2)
#define ZOO_SMB_ERROR_RINGBUF_UNDERFLOW ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_DATA, 3)
#define ZOO_SMB_ERROR_RINGBUF_INVALID_MAGIC ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_RING_BUFFER, ZOO_SMB_RINGBUF_DATA, 4)

    // ==============================================================================
    // SUBSCRIPTION ERRORS (Category 16)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_SUBSCRIPTION_MANAGEMENT = 0, /**< Subscription management */
        ZOO_SMB_SUBSCRIPTION_MATCHING = 1,   /**< Message matching */
        ZOO_SMB_SUBSCRIPTION_DELIVERY = 2,   /**< Message delivery */
        ZOO_SMB_SUBSCRIPTION_FILTER = 3,     /**< Message filtering */
    } ZOO_SMB_SUBSCRIPTION_SUBCATEGORY;

// Subscription management errors
#define ZOO_SMB_ERROR_SUBSCRIPTION_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_MANAGEMENT, 1)
#define ZOO_SMB_ERROR_SUBSCRIPTION_EXISTS ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_MANAGEMENT, 2)
#define ZOO_SMB_ERROR_SUBSCRIPTION_LIMIT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_MANAGEMENT, 3)

// Message matching errors
#define ZOO_SMB_ERROR_SUBSCRIPTION_NO_MATCH ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_MATCHING, 1)
#define ZOO_SMB_ERROR_SUBSCRIPTION_PATTERN_INVALID ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_MATCHING, 2)

// Message delivery errors
#define ZOO_SMB_ERROR_SUBSCRIPTION_DELIVERY_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_DELIVERY, 1)
#define ZOO_SMB_ERROR_SUBSCRIPTION_QUEUE_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_DELIVERY, 2)

// Message filtering errors
#define ZOO_SMB_ERROR_SUBSCRIPTION_FILTER_INVALID ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_FILTER, 1)
#define ZOO_SMB_ERROR_SUBSCRIPTION_FILTER_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_SUBSCRIPTION, ZOO_SMB_SUBSCRIPTION_FILTER, 2)

    // ==============================================================================
    // PUBLICATION ERRORS (Category 17)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_PUBLICATION_SEND = 0,       /**< Message sending */
        ZOO_SMB_PUBLICATION_ROUTING = 1,    /**< Message routing */
        ZOO_SMB_PUBLICATION_QOS = 2,        /**< Quality of service */
        ZOO_SMB_PUBLICATION_THROTTLING = 3, /**< Rate limiting */
    } ZOO_SMB_PUBLICATION_SUBCATEGORY;

// Message sending errors
#define ZOO_SMB_ERROR_PUBLICATION_SEND_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PUBLICATION, ZOO_SMB_PUBLICATION_SEND, 1)
#define ZOO_SMB_ERROR_PUBLICATION_QUEUE_FULL ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PUBLICATION, ZOO_SMB_PUBLICATION_SEND, 2)

// Message routing errors
#define ZOO_SMB_ERROR_PUBLICATION_NO_SUBSCRIBERS ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PUBLICATION, ZOO_SMB_PUBLICATION_ROUTING, 1)
#define ZOO_SMB_ERROR_PUBLICATION_ROUTING_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PUBLICATION, ZOO_SMB_PUBLICATION_ROUTING, 2)

// QoS errors
#define ZOO_SMB_ERROR_PUBLICATION_QOS_VIOLATION ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PUBLICATION, ZOO_SMB_PUBLICATION_QOS, 1)
#define ZOO_SMB_ERROR_PUBLICATION_QOS_NOT_SUPPORTED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PUBLICATION, ZOO_SMB_PUBLICATION_QOS, 2)

// Rate limiting errors
#define ZOO_SMB_ERROR_PUBLICATION_RATE_EXCEEDED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PUBLICATION, ZOO_SMB_PUBLICATION_THROTTLING, 1)
#define ZOO_SMB_ERROR_PUBLICATION_THROTTLED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_PUBLICATION, ZOO_SMB_PUBLICATION_THROTTLING, 2)

    // ==============================================================================
    // DISCOVERY ERRORS (Category 18)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_DISCOVERY_ANNOUNCEMENT = 0, /**< Service announcement */
        ZOO_SMB_DISCOVERY_LOOKUP = 1,       /**< Service lookup */
        ZOO_SMB_DISCOVERY_RESOLUTION = 2,   /**< Name resolution */
        ZOO_SMB_DISCOVERY_HEALTH = 3,       /**< Health checking */
    } ZOO_SMB_DISCOVERY_SUBCATEGORY;

// Service announcement errors
#define ZOO_SMB_ERROR_DISCOVERY_ANNOUNCE_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DISCOVERY, ZOO_SMB_DISCOVERY_ANNOUNCEMENT, 1)
#define ZOO_SMB_ERROR_DISCOVERY_REGISTER_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DISCOVERY, ZOO_SMB_DISCOVERY_ANNOUNCEMENT, 2)

// Service lookup errors
#define ZOO_SMB_ERROR_DISCOVERY_SERVICE_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DISCOVERY, ZOO_SMB_DISCOVERY_LOOKUP, 1)
#define ZOO_SMB_ERROR_DISCOVERY_LOOKUP_TIMEOUT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DISCOVERY, ZOO_SMB_DISCOVERY_LOOKUP, 2)

// Name resolution errors
#define ZOO_SMB_ERROR_DISCOVERY_NAME_NOT_FOUND ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DISCOVERY, ZOO_SMB_DISCOVERY_RESOLUTION, 1)
#define ZOO_SMB_ERROR_DISCOVERY_RESOLUTION_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DISCOVERY, ZOO_SMB_DISCOVERY_RESOLUTION, 2)

// Health checking errors
#define ZOO_SMB_ERROR_DISCOVERY_HEALTH_CHECK_FAILED ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DISCOVERY, ZOO_SMB_DISCOVERY_HEALTH, 1)
#define ZOO_SMB_ERROR_DISCOVERY_SERVICE_UNHEALTHY ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_DISCOVERY, ZOO_SMB_DISCOVERY_HEALTH, 2)

    // ==============================================================================
    // TIMEOUT ERRORS (Category 27)
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_TIMEOUT_OPERATION = 0,  /**< Operation timeouts */
        ZOO_SMB_TIMEOUT_CONNECTION = 1, /**< Connection timeouts */
        ZOO_SMB_TIMEOUT_RESPONSE = 2,   /**< Response timeouts */
        ZOO_SMB_TIMEOUT_HEARTBEAT = 3,  /**< Heartbeat timeouts */
    } ZOO_SMB_TIMEOUT_SUBCATEGORY;

// Timeout errors
#define ZOO_SMB_ERROR_TIMEOUT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TIMEOUT, ZOO_SMB_TIMEOUT_OPERATION, 1)
#define ZOO_SMB_ERROR_CONNECT_TIMEOUT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TIMEOUT, ZOO_SMB_TIMEOUT_CONNECTION, 1)
#define ZOO_SMB_ERROR_RESPONSE_TIMEOUT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TIMEOUT, ZOO_SMB_TIMEOUT_RESPONSE, 1)
#define ZOO_SMB_ERROR_HEARTBEAT_TIMEOUT ZOO_SMB_MAKE_ERROR(ZOO_SMB_CATEGORY_TIMEOUT, ZOO_SMB_TIMEOUT_HEARTBEAT, 1)

    // ==============================================================================
    // ERROR SEVERITY LEVELS
    // ==============================================================================
    typedef enum
    {
        ZOO_SMB_SEVERITY_INFO = 0,     /**< Informational */
        ZOO_SMB_SEVERITY_WARNING = 1,  /**< Warning */
        ZOO_SMB_SEVERITY_ERROR = 2,    /**< Error */
        ZOO_SMB_SEVERITY_CRITICAL = 3, /**< Critical error */
        ZOO_SMB_SEVERITY_FATAL = 4,    /**< Fatal error */
    } ZOO_SMB_ERROR_SEVERITY;


    // ==============================================================================
    // CORE FUNCTIONS
    // ==============================================================================

    /**
     * @brief Get human-readable error string
     * @param error Error code
     * @return Error description string
     */
    const char* zoo_smb_get_error_string(ZOO_ERROR_TYPE error);

    /**
     * @brief Get error category name
     * @param category Error category
     * @return Category name string
     */
    const char* zoo_smb_get_category_string(ZOO_SMB_ERROR_CATEGORY category);

    /**
     * @brief Get error severity for given error code
     * @param error Error code
     * @return Error severity level
     */
    ZOO_SMB_ERROR_SEVERITY zoo_smb_get_error_severity(ZOO_ERROR_TYPE error);

    /**
     * @brief Get and clear last error for current thread
     * @return Last error code
     */
    ZOO_ERROR_TYPE zoo_smb_get_last_error(void);

    /**
     * @brief Set last error for current thread
     * @param error Error code to set
     */
    void zoo_smb_set_last_error(ZOO_ERROR_TYPE error);

    /**
     * @brief Clear last error for current thread
     */
    void zoo_smb_clear_last_error(void);

#ifdef __cplusplus
}
#endif

#endif /* ZOO_SMB_ERROR_H */